from PyQt5 import QtCore, QtGui, QtWidgets
import os
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(1060, 700)
        MainWindow.setMinimumSize(QtCore.QSize(0, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1060, 700))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(36, 203, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 40, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 203, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 40, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(36, 203, 240))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        MainWindow.setPalette(palette)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        MainWindow.setWindowTitle("HI6Cypher")
        icon = QtGui.QIcon()
        main_icon = f"{os.getcwd()}/icons/main.png" # to find icon path
        icon.addPixmap(QtGui.QPixmap(main_icon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setAccessibleName("")
        MainWindow.setAccessibleDescription("")
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonTextOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.plainTextEdit_information = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_information.setGeometry(QtCore.QRect(10, 10, 141, 621))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.plainTextEdit_information.setFont(font)
        self.plainTextEdit_information.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.plainTextEdit_information.setToolTip("")
        self.plainTextEdit_information.setFrameShape(QtWidgets.QFrame.Box)
        self.plainTextEdit_information.setFrameShadow(QtWidgets.QFrame.Raised)
        self.plainTextEdit_information.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_information.setReadOnly(True)
        self.plainTextEdit_information.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.plainTextEdit_information.setBackgroundVisible(False)
        self.plainTextEdit_information.setObjectName("plainTextEdit_information")
        self.textBrowser_main = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser_main.setGeometry(QtCore.QRect(160, 10, 891, 621))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 28, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 28, 90))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.textBrowser_main.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.textBrowser_main.setFont(font)
        self.textBrowser_main.setToolTip("")
        self.textBrowser_main.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_main.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textBrowser_main.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textBrowser_main.setObjectName("textBrowser_main")
        self.lineEdit_write = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_write.setEnabled(True)
        self.lineEdit_write.setGeometry(QtCore.QRect(160, 640, 841, 40))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_write.setFont(font)
        self.lineEdit_write.setTabletTracking(True)
        self.lineEdit_write.setToolTip("")
        self.lineEdit_write.setAutoFillBackground(False)
        self.lineEdit_write.setStyleSheet("")
        self.lineEdit_write.setInputMask("")
        self.lineEdit_write.setText("")
        self.lineEdit_write.setFrame(True)
        self.lineEdit_write.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_write.setCursorPosition(0)
        self.lineEdit_write.setObjectName("lineEdit_write")
        self.pushButton_snap = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_snap.setGeometry(QtCore.QRect(1010, 640, 40, 40))
        self.pushButton_snap.setToolTip("")
        self.pushButton_snap.setToolTipDuration(-1)
        self.pushButton_snap.setAutoFillBackground(False)
        self.pushButton_snap.setText("")
        icon1 = QtGui.QIcon()
        snap_icon = f"{os.getcwd()}/icons/snap.png" # to find icon path
        icon1.addPixmap(QtGui.QPixmap(snap_icon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_snap.setIcon(icon1)
        self.pushButton_snap.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_snap.setAutoDefault(True)
        self.pushButton_snap.setDefault(True)
        self.pushButton_snap.setFlat(False)
        self.pushButton_snap.setObjectName("pushButton_snap")
        self.pushButton_help = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_help.setGeometry(QtCore.QRect(10, 640, 40, 40))
        self.pushButton_help.setToolTip("")
        self.pushButton_help.setToolTipDuration(-1)
        self.pushButton_help.setText("")
        icon2 = QtGui.QIcon()
        help_icon = f"{os.getcwd()}/icons/help.png" # to find icon path
        icon2.addPixmap(QtGui.QPixmap(help_icon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_help.setIcon(icon2)
        self.pushButton_help.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_help.setAutoRepeatInterval(100)
        self.pushButton_help.setObjectName("pushButton_help")
        self.pushButton_about = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_about.setGeometry(QtCore.QRect(60, 640, 40, 40))
        self.pushButton_about.setToolTip("")
        self.pushButton_about.setToolTipDuration(-1)
        self.pushButton_about.setText("")
        icon3 = QtGui.QIcon()
        about_icon = f"{os.getcwd()}/icons/about.png"
        icon3.addPixmap(QtGui.QPixmap(about_icon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_about.setIcon(icon3)
        self.pushButton_about.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_about.setObjectName("pushButton_about")
        self.pushButton_save = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_save.setGeometry(QtCore.QRect(110, 640, 40, 40))
        self.pushButton_save.setToolTip("")
        self.pushButton_save.setToolTipDuration(-1)
        self.pushButton_save.setText("")
        icon4 = QtGui.QIcon()
        save_icon = f"{os.getcwd()}/icons/save.png" # to find icon path
        icon4.addPixmap(QtGui.QPixmap(save_icon), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_save.setIcon(icon4)
        self.pushButton_save.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_save.setObjectName("pushButton_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pushButton_snap.clicked.connect(self.pushButton_snap.click)
        self.pushButton_save.clicked.connect(self.pushButton_save.click)
        self.pushButton_help.clicked.connect(self.help_form) # runs help module
        self.pushButton_about.clicked.connect(self.pushButton_about.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        self.plainTextEdit_information.setPlainText(_translate("MainWindow", ""))
        self.textBrowser_main.setHtml(_translate("MainWindow", ""))
        self.pushButton_snap.setAccessibleName(_translate("MainWindow", "Snap!"))
        self.pushButton_snap.setAccessibleDescription(_translate("MainWindow", "Snap!"))
        self.pushButton_help.setAccessibleName(_translate("MainWindow", "help"))
        self.pushButton_help.setAccessibleDescription(_translate("MainWindow", "help"))
        self.pushButton_about.setAccessibleName(_translate("MainWindow", "about"))
        self.pushButton_about.setAccessibleDescription(_translate("MainWindow", "about"))
        self.pushButton_save.setAccessibleName(_translate("MainWindow", "save"))
        self.pushButton_save.setAccessibleDescription(_translate("MainWindow", "save"))

    def help_form(self) :
        from help import Ui_Form
        
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
Form = QtWidgets.QWidget()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())